CREATE TABLE `tb_projects` (
  `idproject` int(11) NOT NULL AUTO_INCREMENT,
  `desproject` varchar(128) NOT NULL,
  `descode` varchar(32) NOT NULL COMMENT 'Nº do projeto',
  `idclient` int(11) NOT NULL,
  `idsalesman` int(11) NOT NULL,
  `dtdue` date DEFAULT NULL,
  `dtdelivery` date DEFAULT NULL,
  `idcalendar` int(11) NOT NULL,
  `idformat` int(11) NOT NULL,
  `idstandtype` int(11) NOT NULL,
  `vlsum` decimal(10,2) NOT NULL,
  `desdescription` text,
  `dtregister` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`idproject`),
  KEY `fk_projectsformats_idx` (`idformat`),
  KEY `fk_projects_persons_idx` (`idclient`),
  KEY `fk_projects_salesman_idx` (`idsalesman`),
  KEY `fk_projects_projectsstandstypes_idx` (`idstandtype`),
  CONSTRAINT `fk_projects_clients` FOREIGN KEY (`idclient`) REFERENCES `tb_persons` (`idperson`) ON DELETE NO ACTION ON UPDATE NO ACTION,
  CONSTRAINT `fk_projects_projectsstandstypes` FOREIGN KEY (`idstandtype`) REFERENCES `tb_projectsstandstypes` (`idstandtype`) ON DELETE NO ACTION ON UPDATE NO ACTION,
  CONSTRAINT `fk_projects_salesman` FOREIGN KEY (`idsalesman`) REFERENCES `tb_persons` (`idperson`) ON DELETE NO ACTION ON UPDATE NO ACTION,
  CONSTRAINT `fk_projectsformats` FOREIGN KEY (`idformat`) REFERENCES `tb_projectsformats` (`idformat`) ON DELETE NO ACTION ON UPDATE NO ACTION
) ENGINE=InnoDB DEFAULT CHARSET=latin1