CREATE TABLE `tb_placesdata` (
  `idplace` int(11) NOT NULL,
  `desplace` varchar(128) NOT NULL,
  `idplacefather` int(11) DEFAULT NULL,
  `desplacefather` varchar(128) DEFAULT NULL,
  `idplacetype` int(11) NOT NULL,
  `desplacetype` varchar(128) NOT NULL,
  `idaddresstype` int(11) DEFAULT NULL,
  `desaddresstype` varchar(128) DEFAULT NULL,
  `idaddress` int(11) DEFAULT NULL,
  `desaddress` varchar(128) DEFAULT NULL,
  `desnumber` varchar(16) DEFAULT NULL,
  `desdistrict` varchar(64) DEFAULT NULL,
  `descity` varchar(64) DEFAULT NULL,
  `desstate` varchar(32) DEFAULT NULL,
  `descountry` varchar(32) DEFAULT NULL,
  `descep` char(8) DEFAULT NULL,
  `descomplement` varchar(32) DEFAULT NULL,
  `idcoordinate` int(11) DEFAULT NULL,
  `vllatitude` decimal(20,17) DEFAULT NULL,
  `vllongitude` decimal(20,17) DEFAULT NULL,
  `nrzoom` tinyint(4) DEFAULT NULL,
  `dtregister` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`idplace`),
  KEY `idplacefather` (`idplacefather`),
  KEY `idplacetype` (`idplacetype`),
  KEY `idaddress` (`idaddress`),
  KEY `idaddresstype` (`idaddresstype`),
  KEY `idcoordinate` (`idcoordinate`),
  CONSTRAINT `FK_placesdata_places_place` FOREIGN KEY (`idplace`) REFERENCES `tb_places` (`idplace`),
  CONSTRAINT `FK_placesdata_places_placefather` FOREIGN KEY (`idplacefather`) REFERENCES `tb_places` (`idplace`),
  CONSTRAINT `FK_placesdata_placestypes` FOREIGN KEY (`idplacetype`) REFERENCES `tb_placestypes` (`idplacetype`),
  CONSTRAINT `FK_placesdata_addresses` FOREIGN KEY (`idaddress`) REFERENCES `tb_addresses` (`idaddress`),
  CONSTRAINT `FK_placesdata_addressestypes` FOREIGN KEY (`idaddresstype`) REFERENCES `tb_addressestypes` (`idaddresstype`),
  CONSTRAINT `FK_placesdata_coordinates` FOREIGN KEY (`idcoordinate`) REFERENCES `tb_coordinates` (`idcoordinate`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8