INSERT INTO tb_menus (idmenu,idmenufather,desmenu,desicon,deshref,nrorder,nrsubmenus) VALUES
(2,NULL,'Sistema','md-code-setting','',7,3),
(3,NULL,'Administração','md-settings','',8,9),
(4,NULL,'Pessoas','md-accounts','/persons',9,NULL),
(5,3,'Tipos','md-collection-item','',NULL,20),
(6,3,'Menu','','/system/menu',1,NULL),
(7,3,'Usuários','','/system/users',2,NULL),
(8,3,'Configurações','','/system/configurations',4,NULL),
(9,2,'SQL to CLASS','','/system/sql-to-class',NULL,NULL),
(10,2,'Template','','/../res/theme/material/base/html/index.html',1,NULL),
(11,2,'Exemplos','','',2,1),
(12,11,'Upload de Arquivos','','/exemplos/upload',NULL,NULL),
(13,3,'Permissões','','/permissions',3,NULL),
(14,NULL,'Produtos','md-devices','/products',10,NULL),
(15,5,'Endereços Tipos','','/addresses-types',NULL,NULL),
(16,5,'Usuário Tipos','','/users-types',1,NULL),
(17,5,'Documentos Tipos','','/documents-types',2,NULL),
(18,5,'Lugares Tipos','','/places-types',3,NULL),
(19,5,'Cupons Tipos','','/cupons-types',4,NULL),
(20,5,'Produtos Tipos','','/products-types',5,NULL),
(21,5,'Pedidos Status','','/orders-status',6,NULL),
(22,5,'Pessoas Tipos','','/persons-types',7,NULL),
(23,5,'Contatos Tipos','','/contacts-types',8,NULL),
(24,5,'Gateways','','/gateways',9,NULL),
(25,5,'Historicos Tipos','','/logs-types',10,NULL),
(26,5,'Formas de Pagamentos','','/formas-pagamentos',11,NULL),
(27,5,'Pessoas Valores Campos','','/persons-valuesfields',12,NULL),
(28,5,'Configurações Tipos','','/configurations-types',13,NULL),
(29,5,'Carousels Items Tipos','','/carousels-types',15,NULL),
(30,5,'Pedidos Negociações Tipos','','/ordersnegotiationstypes',14,NULL),
(31,NULL,'Pedidos','md-money-box','/orders',11,NULL),
(32,NULL,'Carrinhos','md-shopping-cart','/carts',12,NULL),
(33,NULL,'Lugares','md-city','/places',13,NULL),
(34,NULL,'Site','md-view-web','',14,3),
(35,34,'Menu','','/site/menu',NULL,NULL),
(36,NULL,'Cursos','md-book','/courses',15,NULL),
(37,34,'Carousels','','/carousels',1,NULL),
(38,3,'Países','','/countries',5,NULL),
(39,3,'Estados','','/states',6,NULL),
(40,3,'Cidades','','/cities',7,NULL),
(41,3,'Arquivos','','/files',8,NULL),
(42,5,'Categorias de Pessoas','','/persons-categories-types',16,NULL),
(43,5,'Histórico de Usuário','','/userslogs-types',17,NULL),
(44,5,'Transações tipos','','/transactions-types',18,NULL),
(45,NULL,'URLs','md-link','/urls',16,NULL),
(46,34,'Blog','','',2,5),
(47,46,'Principal','','/blog/posts',NULL,NULL),
(48,46,'Novo Post','','/blog/posts/new',1,NULL),
(49,46,'Categorias','','/blog/categories',2,NULL),
(50,46,'Tags','','/blog/tags',3,NULL),
(51,46,'Comentários','','/blog/comments',4,NULL),
(52,NULL,'Serviço de E-mails','md-email','/emails',18,NULL),
(53,NULL,'Fluxo de Caixa','md-money-box','/fluxo-de-caixa',17,NULL),
(54,NULL,'Time','','',19,2),
(55,54,'Cargos','','/team/jobs-positions',NULL,NULL),
(56,54,'Colaboradores','','/team/workers',1,NULL),
(57,NULL,'Redes Sociais','','/social-networks',20,NULL),
(58,NULL,'Categorias','','/categories',21,NULL),
(59,NULL,'Visão Geral','md-home','/',NULL,NULL),
(60,NULL,'Vendas','md-assignment-o','',4,4),
(61,NULL,'Compras','md-shopping-cart','',5,4),
(62,NULL,'Financeiro','md-money-box','',6,5),
(63,60,'Clientes','md-accounts','/clients',1,NULL),
(64,60,'Produtos','md-devices','/products',2,NULL),
(65,60,'Vendas e Orçamentos','md-assignment','/sales-orders',NULL,NULL),
(66,60,'Estoque','md-collection-bookmark','/stock',3,NULL),
(67,61,'Compras','md-shopping-basket','/purshaces',NULL,NULL),
(68,61,'Fornecedores','md-assignment-returned','/providers',1,NULL),
(69,61,'Produtos','md-devices','/products',2,NULL),
(70,61,'Estoque','md-collection-bookmark','/stock',3,NULL),
(71,62,'Contas','md-folder-outline','/accounts',NULL,NULL),
(72,62,'Extrato','md-balance-wallet','/bank-statement',1,NULL),
(73,62,'Contas a Pagar','md-money-off','/bills-to-pay',2,NULL),
(74,62,'Contas a Receber','md-money','/bills-to-receive',3,NULL),
(75,62,'Categorias','md-folder-outline','/financial-categories',4,NULL),
(76,NULL,'Eventos','md-calendar','',1,3),
(77,76,'Calendário de Eventos','md-calendar-alt','/events',2,NULL),
(78,76,'Organizadores','md-accounts-alt','/events-organizers',1,NULL),
(79,76,'Frequências','md-calendar-alt','/events-frequencies',NULL,NULL),
(80,NULL,'Materiais','md-labels','',2,1),
(81,80,'Materiais','md-labels','/materials',NULL,NULL),
(82,NULL,'Projetos','md-ruler','',3,1),
(83,82,'Projetos & Briefings','md-ruler','/projects',NULL,NULL),
(84,5,'Materiais Tipos','md-chevron-right','/materiais-types',19,NULL);